CREATE TABLE RESTAURANTS(
R_NAME TEXT,
R_NEIGHBOURHOOD TEXT,
R_CUISINE TEXT,
R_REVIEW REAL,
R_PRICE TEXT,
R_HEALTH TEXT);

INSERT INTO RESTAURANTS(R_NAME , R_NEIGHBOURHOOD , R_CUISINE , R_REVIEW , R_PRICE , R_HEALTH)
VALUES
('PETER' , 'BROOKLYN' , 'STEAK' , 5.0 , '$$$' , 'A'),
('JONGRO' , 'MIDTOWN' , 'KOREAN' , 3.4 , '$$' , 'A'),
('POCHA' , 'MIDTOWN' , 'PIZZA' , 4.0 , '$$$' , 'B'),
('LIGHTHOUSE' , 'QUEENS' , 'CHINESE' , 4.0 , '$' , 'A'),
('MINCA' , 'DOWMTOWN' , 'AMERICAN' , 4.6 , '$$$' , ''),
('MAREA' , 'CHINATOWN' , 'CHINESE' , 3.0 , '$$' , ''),
('DIRTY CANDY' , 'UPTOWN' , 'ITALIAN' , 4.9 , '$$$$' , 'B' ),
('BI FARA PIZZA' , 'BROOKLYN' , 'PIZZA' , 4.0 , '$$$' , 'A'),
('GOLDEN UNICORN' , 'UPTOWN' , 'ITALIAN' , 5.0 , '$$$$$' , 'SSA');

SELECT * FROM RESTAURANTS;

SELECT DISTINCT R_NEIGHBOURHOOD FROM RESTAURANTS;

SELECT DISTINCT R_CUISINE FROM RESTAURANTS;

SELECT * FROM RESTAURANTS WHERE R_CUISINE = 'CHINESE';

SELECT * FROM RESTAURANTS WHERE R_REVIEW >= 4;

SELECT * FROM RESTAURANTS WHERE R_CUISINE = 'ITALIAN' AND R_PRICE = '$$$';

SELECT * FROM RESTAURANTS WHERE R_NAME LIKE '%CANDY%' ;

SELECT * FROM RESTAURANTS
WHERE R_NEIGHBOURHOOD IN ('MIDTOWN' , 'DOWNTOWN' , 'CHINATOWN');

SELECT * FROM RESTAURANTS ORDER BY R_REVIEW DESC LIMIT 4;

DROP TABLE RESTAURANTS;